### ISSUE TITLE
File says it's uploaded, but the data is not there

### ISSUE THREAD

**Issue by samjhill** [storj-thirdparty/uplink-nodejs#16]
Thank you for making this library!

I'm having an issue where the library says the file is uploaded, but when I fetch the objects in the bucket, it lists the name, but the content-length of each object is 0. 

```
sam.hill@Sam-Hill maple (main) $ node index.js
✅ successfully connected to Tardigrade
File Uploaded On Storj:  100.0000  %

Object stored on storj V3 network successfully
file size:  409
Finished uploading!
{ custom: { entries: { '0': '' }, count: 0 },
  system: { created: 0, expires: 0, content_length: 0 },
  is_prefix: 0,
  key: '2020-10-19T22:53:25.695Z.zip' }
{ custom: { entries: { '0': '' }, count: 0 },
  system: { created: 0, expires: 0, content_length: 0 },
  is_prefix: 1,
  key: '/' }
{ custom: { entries: { '0': '' }, count: 0 },
  system: { created: 0, expires: 0, content_length: 0 },
  is_prefix: 0,
  key: '2020-10-19T22:38:07.366Z.zip' }
{ custom: { entries: { '0': '' }, count: 0 },
  system: { created: 0, expires: 0, content_length: 0 },
  is_prefix: 1,
  key: 'filepath/' }
{ custom: { entries: { '0': '' }, count: 0 },
  system: { created: 0, expires: 0, content_length: 0 },
  is_prefix: 0,
  key: '2020-10-19T22:40:38.409Z.zip' }
{ custom: { entries: { '0': '' }, count: 0 },
  system: { created: 0, expires: 0, content_length: 0 },
  is_prefix: 0,
  key: '2020-10-19T22:47:31.575Z.zip' }
{ custom: { entries: { '0': '' }, count: 0 },
  system: { created: 0, expires: 0, content_length: 0 },
  is_prefix: 0,
  key: '2020-10-19T22:49:57.224Z.zip' }
{ custom: { entries: { '0': '' }, count: 0 },
  system: { created: 0, expires: 0, content_length: 0 },
  is_prefix: 0,
  key: '2020-10-19T22:36:07.822Z.zip' }
{ custom: { entries: { '0': '' }, count: 0 },
  system: { created: 0, expires: 0, content_length: 0 },
  is_prefix: 0,
  key: '2020-10-19T22:54:35.417Z.zip' }
```

And in the Tardigrade dashboard, it says no objects exist.

<img width="1311" alt="Screen Shot 2020-10-19 at 6 59 35 PM" src="https://user-images.githubusercontent.com/1424050/96520514-41223d00-123d-11eb-870f-176089e4fda9.png">

Minimal reproduction of issue:

https://github.com/samjhill/maple

I'd greatly appreciate any advice or help you could give! Thank you in advance.

**Comment by shivamkumar99** [comment]
Hi @samjhill  , you can take reference from HelloStorj example provided in uplink-nodejs

https://github.com/storj-thirdparty/uplink-nodejs/blob/master/HelloStorj.js

we have tested it now. it is working fine. so you can check your code by taking reference from hellostorj example.if issue still persists do let us know.

**Comment by samjhill** [comment]
@shivamkumar99 thank you for the response!

For others who may face this problem, it turns out there is a significant delay from when the network says your file is uploaded until the UI on the Tardigrade dashboard is updated with your new files.
