### ISSUE TITLE
Docs Tutorial is missing a step to upload files

### ISSUE THREAD

**Issue by NemeSnz** [storj-thirdparty/uplink-nodejs#17]
The [Step 8: Upload](https://storj-thirdparty.github.io/uplink-nodejs/#/tutorial?id=step-8-upload) form the tutorial is missing the commit step that is required to upload a file. the commit function `upload.commit` needs to be called after `upload.write`. That should not be omitted in the tutorial.

**Comment by ayush-srivastava-03** [comment]
Updated documentation
