### ISSUE TITLE
Typescript integration

### ISSUE THREAD

**Issue by NemeSnz** [storj-thirdparty/uplink-nodejs#18]
The module is missing a declaration file thus giving an error one using it in a typescript project with the `noImplicitAny` option set.

It should be straight forward to add type definitions since you are already using classes. Solving this issue would improve the DX for anyone using typescript.

Are you taking contributions?

**Comment by kmozurkewich** [comment]
@NemeSnz  -

Thank you for the feedback.

Yes, we always take contributions.  Please feel free to submit a PR.

**Comment by kmozurkewich** [comment]
Hi @NemeSnz - I know the team issued a PR against your repo with some changes.  Can you review so we can complete integration?


Thanks!

**Comment by ayush-srivastava-03** [comment]
Integrated typescript in uplink-nodejs version 1.0.9
