### ISSUE TITLE
mocha as devDependency

### ISSUE THREAD

**Issue by Matheusih** [storj-thirdparty/uplink-nodejs#22]
Is mocha a necessary dependency? 
Couldn't it be moved to devDependencies?

Otherwise it conflicts with typescript projects using jest as testing framework.

**Comment by kmozurkewich** [comment]
@Matheusih - we'll get this feedback in the queue for a new release.  Thanks!

**Comment by ayush-srivastava-03** [comment]
Updated and closed issue on uplink-nodejs version 1.2.0
