### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by avishkarabhishek786** [storj-thirdparty/uplink-nodejs#23]
uplink is setup perfectly. When I run 

`const storj = require("uplink-nodejs");
const libUplink = new storj.Uplink();`

this error is produced-

/vagrant/gunkeeperapp/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /vagrant/gunkeeperapp/node_modules/uplink-nodejs/build/uplink.node
 → /vagrant/gunkeeperapp/node_modules/uplink-nodejs/build/Debug/uplink.node
 → /vagrant/gunkeeperapp/node_modules/uplink-nodejs/build/Release/uplink.node
 → /vagrant/gunkeeperapp/node_modules/uplink-nodejs/out/Debug/uplink.node
 → /vagrant/gunkeeperapp/node_modules/uplink-nodejs/Debug/uplink.node
 → /vagrant/gunkeeperapp/node_modules/uplink-nodejs/out/Release/uplink.node
 → /vagrant/gunkeeperapp/node_modules/uplink-nodejs/Release/uplink.node
 → /vagrant/gunkeeperapp/node_modules/uplink-nodejs/build/default/uplink.node
 → /vagrant/gunkeeperapp/node_modules/uplink-nodejs/compiled/15.6.0/linux/x64/uplink.node
 → /vagrant/gunkeeperapp/node_modules/uplink-nodejs/addon-build/release/install-root/uplink.node
 → /vagrant/gunkeeperapp/node_modules/uplink-nodejs/addon-build/debug/install-root/uplink.node
 → /vagrant/gunkeeperapp/node_modules/uplink-nodejs/addon-build/default/install-root/uplink.node
 → /vagrant/gunkeeperapp/node_modules/uplink-nodejs/lib/binding/node-v88-linux-x64/uplink.node
    at bindings (/vagrant/gunkeeperapp/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/vagrant/gunkeeperapp/node_modules/uplink-nodejs/dist/access.js:6:16)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/vagrant/gunkeeperapp/node_modules/uplink-nodejs/dist/uplink.js:10:21)
    at Module._compile (node:internal/modules/cjs/loader:1108:14) {
  tries: [
    '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/build/uplink.node',
    '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/build/Debug/uplink.node',
    '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/build/Release/uplink.node',
    '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/out/Debug/uplink.node',
    '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/Debug/uplink.node',
    '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/out/Release/uplink.node',
    '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/Release/uplink.node',
    '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/build/default/uplink.node',
    '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/compiled/15.6.0/linux/x64/uplink.node',
    '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/addon-build/release/install-root/uplink.node',
    '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/addon-build/debug/install-root/uplink.node',
    '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/addon-build/default/install-root/uplink.node',
    '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/lib/binding/node-v88-linux-x64/uplink.node'
  ]

**Comment by kmozurkewich** [comment]
Hi @avishkarabhishek786 ! - thanks for the note.

What process did you use to install?  Also what is the output of

`npm test`

**Comment by avishkarabhishek786** [comment]
Hi @kmozurkewich 

I am running this app in a VM ("ubuntu/xenial64")

Installed nodejs - v15.6.0

installed node-gyp

`npm install`

Then I got an error make command not found. So I installed make by 
`sudo apt-get install build-essential`

Then I ran 
`node index`
which produced above error.

Also `npm test` in /node_modules/uplink-nodejs returned error "No test files found". I edited package.json test script to
"mocha 'test/testcase.ts' --recursive --timeout 60000 --exit"

On running npm test again it returned same error - Could not locate the bindings file

**Comment by ayush-srivastava-03** [comment]
Hi @avishkarabhishek786 , 
1) are you getting same error while running HelloStorj.js example ?
you can find HelloStorj Example :
https://github.com/storj-thirdparty/uplink-nodejs/blob/master/HelloStorj.js

2) Can you please share list of files in following folder :
```
$PROJECTROOTDIR/node_modules/uplink-nodejs/build/Release
```

**Comment by avishkarabhishek786** [comment]
Hi @ayush-srivastava-03 

1. Yes, same error
2. binding.Makefile  config.gypi  Makefile  Release  uplink.target.mk

**Comment by ayush-srivastava-03** [comment]
@avishkarabhishek786 can you please share output of npm install command ?
You can take reference from the following link for installing dependencies :
https://github.com/storj-thirdparty/uplink-nodejs/blob/master/Dockerfile

**Comment by avishkarabhishek786** [comment]
vagrant@ubuntu-xenial:/vagrant/myApp/node_modules/uplink-nodejs$ npm install

> uplink-nodejs@1.0.9 preinstall
> make

make: 'build' is up to date.

> uplink-nodejs@1.0.9 install
> (node-gyp configure) && (node-gyp rebuild)

gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.6.0 | linux | x64
gyp info find Python using Python version 3.5.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/vagrant/.cache/node-gyp/15.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/vagrant/.cache/node-gyp/15.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/vagrant/gunkeeperapp/node_modules/uplink-nodejs/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/vagrant/.cache/node-gyp/15.6.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/vagrant/gunkeeperapp/node_modules/uplink-nodejs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.6.0 | linux | x64
gyp info find Python using Python version 3.5.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/vagrant/.cache/node-gyp/15.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/vagrant/.cache/node-gyp/15.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/vagrant/gunkeeperapp/node_modules/uplink-nodejs/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/vagrant/.cache/node-gyp/15.6.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/vagrant/gunkeeperapp/node_modules/uplink-nodejs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/build'
make: Warning: File 'uplink.target.mk' has modification time 0.89 s in the future
  CXX(target) Release/obj.target/uplink/libUplink.o
In file included from ../libUplink.h:5:0,
                 from ../libUplink.cc:6:
../functions/definitions.h:13:27: fatal error: ../libuplinkc.h: No such file or directory
compilation terminated.
uplink.target.mk:125: recipe for target 'Release/obj.target/uplink/libUplink.o' failed
make: *** [Release/obj.target/uplink/libUplink.o] Error 1
make: Leaving directory '/vagrant/gunkeeperapp/node_modules/uplink-nodejs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/vagrant/gunkeeperapp/node_modules/uplink-nodejs/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:379:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:285:12)
gyp ERR! System Linux 4.4.0-201-generic
gyp ERR! command "/usr/bin/node" "/vagrant/gunkeeperapp/node_modules/uplink-nodejs/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /vagrant/gunkeeperapp/node_modules/uplink-nodejs
gyp ERR! node -v v15.6.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /vagrant/gunkeeperapp/node_modules/uplink-nodejs
npm ERR! command failed
npm ERR! command sh -c (node-gyp configure) && (node-gyp rebuild)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2021-02-04T12_51_17_176Z-debug.log

**Comment by avishkarabhishek786** [comment]
@ayush-srivastava-03 

`cat /home/vagrant/.npm/_logs/2021-02-04T12_51_17_176Z-debug.log`

50 verbose stack Error: command failed
50 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
50 verbose stack     at ChildProcess.emit (node:events:379:20)
50 verbose stack     at maybeClose (node:internal/child_process:1065:16)
50 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:296:5)
51 verbose pkgid uplink-nodejs@1.0.9
52 verbose cwd /vagrant/gunkeeperapp/node_modules/uplink-nodejs
53 verbose Linux 4.4.0-201-generic
54 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
55 verbose node v15.6.0
56 verbose npm  v7.4.0
57 error code 1
58 error path /vagrant/gunkeeperapp/node_modules/uplink-nodejs
59 error command failed
60 error command sh -c (node-gyp configure) && (node-gyp rebuild)
61 verbose exit 1

**Comment by joeyfigaro** [comment]
@ayush-srivastava-03 get this figured out?
