### ISSUE TITLE
why importing 'uplink-nodejs' changes current working directory ?

### ISSUE THREAD

**Issue by siva2204** [storj-thirdparty/uplink-nodejs#29]
I have been working on the integration of storj with meteor js framework Applications, after importing uplink-nodejs, CWD is changed to /home/Projects/node_modules/uplink-nodejs/dist but I don't want my CWD to be changed. why it's changing the working directory?

**Comment by Koellewe** [comment]
I agree this is weird behaviour. Since web-based js isn't allowed to modify or access disk, it would be much more useful if the library was configurable to not touch the filesystem at all (e.g. stream data into/out of memory, so that it can be stored by the calling dev).

**Comment by ayush-srivastava-03** [comment]
Resolved. Readme updated.
