### ISSUE TITLE
Issues in the example code

### ISSUE THREAD

**Issue by keshavg96** [storj-thirdparty/uplink-nodejs#3]
When I ran the HelloStorj.js file using the command **node HelloStorj.js**  I encountered the following issues:

1. The _libUplink.request_access_with_passphrase_ function returns a Promise and so there should either be an async / await tag to wait for the promise to be resolved or a then / catch .

2. The _accessResult_ object obtained from the _request_access_with_passphrase_ function does not contain a error object and thus logs an error **cannot read message of undefined**

3. The example code shows an error **libUplink.open_project is not a function**. After some digging around I found the function can be accessed through the _accessResult_ obj obtained from the _request_access_with_passphrase_ function.
 

Is there another way to run the file or am I missing something here?

**Comment by shivamkumar99** [comment]
@keshavg96 
1) It seems you are trying to run older version of HelloStorj on new version of bindings (v1.0.4). You can find latest example inside node_module/uplink-nodejs
2) New version of binding doesn't return error object . it returns promise which either will be rejected or resolved.
3) Function which accepts access is binded to access object similary function which accept project is binded to project function.

**Comment by keshavg96** [comment]
@shivamkumar99 

Thanks for the help. I was trying to run the file present on the master branch of this repo.
