### ISSUE TITLE
Github hosted storj documentation: some pages not available

### ISSUE THREAD

**Issue by bnn1** [storj-thirdparty/uplink-nodejs#42]
On the docs website https://storj-thirdparty.github.io/uplink-nodejs/#/
pages [uplink-nodejs API Documentation](https://storj-thirdparty.github.io/api-doc/index.html) from the side menu and [uplink-nodejs API Documentation](https://storj-thirdparty.github.io/documentation.html) from the *documentation* dropdown are not available
![image](https://user-images.githubusercontent.com/55663639/149620492-f422b048-572d-4eea-9799-a39f111be403.png)

**Comment by kmozurkewich** [comment]
fixed.
