### ISSUE TITLE
public link for tardigrade.io

### ISSUE THREAD

**Issue by fauzan121002** [storj-thirdparty/uplink-nodejs#9]
how to get this link after uploading some-file.txt in uplink-nodejs? is there no way?

`https://link.tardigradeshare.io/random-string/bucket-name/some-file.txt`

https://documentation.tardigrade.io/getting-started/sharing-your-first-object/share-a-restricted-access-to-an-object

https://documentation.tardigrade.io/api-reference/storj-client-libraries

**Comment by calebcase** [comment]
This isn't formalized in the libuplink API. It is currently only something that the uplink CLI does:
https://github.com/storj/storj/blob/master/cmd/uplink/cmd/share.go#L155

We are thinking about whether it makes sense to add this to the library or not. In the meantime I recommend replicating this logic in your application.

**Comment by calebcase** [comment]
@fauzan121002 we discussed this internally and determined that this shouldn't go into the library yet. Long term I suspect we will have a function here, but we aren't ready for it yet. The sorry for the extra work this causes you.

**Comment by ifraixedes** [comment]
I'm closing this issue because unfortunately, the feature isn't in the current roadmap.
